[workspace]
resolver = "2"

members = [
    "contract"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.dependencies.soroban-sdk]
# version = "0.4.3"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "649798756ca58c670d6fd246f33c860315717b50"

[workspace.dependencies.soroban-auth]
# version = "0.4.3"
git = "https://github.com/stellar/rs-soroban-sdk"
rev = "649798756ca58c670d6fd246f33c860315717b50"

[workspace.dependencies.stellar-strkey]
version = "0.0.7"
git = "https://github.com/stellar/rs-stellar-strkey"
rev = "6e9bb10"

[workspace.dependencies.stellar-xdr]
version = "0.0.12"
git = "https://github.com/stellar/rs-stellar-xdr"
rev = "154e07e"
default-features = false