[workspace]
resolver = "2"

members = [
    "contract"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[workspace.dependencies.soroban-sdk]
version = "0.8.4"

[workspace.dependencies.stellar-strkey]
version = "0.0.7"

[workspace.dependencies.stellar-xdr]
version = "0.0.16"
default-features = false